Add `dec!()` macro by example
paupino/rust-decimal pull request #692
Opened 2024-12-10 19:26 UTC by daniel-pfeiffer

As [discussed](https://github.com/paupino/rust-decimal/issues/688), here is a cleaned up, further optimised and integrated new implementation of `dec!`. It is a completely `const` and compile-time drop in replacement. This requires Rust 1.79.

Your `Result<…String…>` is not destructible, i.e. not usable in `const`. Therefore the new parser has its own `Result`, that can be transparently converted by `?`. This also required splitting `try_from_i128_with_scale` which thus became simpler.

For now the parser does only exact in `i128`. Rounding should be addable, if you want to switch parsing completely to this.

Being generic on a smaller type doesn’t currently seem possible in `const`. Should a benchmark show this to be slower than parsing into `u64`, the old and new parsers might continue to coexist, till a solution is found.

2025-01-23 20:21 UTC, paupino requested changes
Sorry for the delay in getting to this - and thank you for putting this together!

Added a couple of comments, however it really boils down to two requested changes I think:

First is to put this behind a feature flag `macros`. That way, we can remove some unnecessary ambiguity (also, making this an opt in feature). It means prelude will keep working until people have a chance to migrate over.

The _other_ thing we should do is clean up the old `macros` folder (i.e. remove it completely). Personally, I think having an opinionated way forward is better - also, since it is a separate crate it should be fine to completely remove (i.e. folks can still use the old crate). Of course, this requires some clean up of the documentation to remove the reference to the crate too.

Thanks again!

2025-01-23 20:21 UTC, paupino commented on src/lib.rs
> +    pub use crate::{dec, Decimal, RoundingStrategy};
If we feature flag it, we'd just need to optionally include it here.

2025-01-23 20:21 UTC, paupino commented on src/str.rs
> +    (#![run_time] $($rest:tt)+) => {
Small nit: typically parameter attributes would not have the exclamation mark (e.g. `#[run_time]`. That said, I wonder if it's worthwhile just splitting this out completely - e.g. `dec_debug!(xyz)` or `debug_dec!(xyz)`

2025-02-04 19:21 UTC, daniel-pfeiffer commented on src/str.rs
> +    (#![run_time] $($rest:tt)+) => {
This emulates an outer attribute, as though it had been written before the macro. Really making one that can be put outside would be a big effort. So I opted for putting it inside, which in Rust is written with an exclamation mark.

It's a little more than debug, also giving dynamic parameters, which is why I called it run_time.

For the feature gate, do you see that as only affecting the prelude, or the overall availability?

2025-02-04 23:05 UTC, paupino commented on src/str.rs
> +    (#![run_time] $($rest:tt)+) => {
Sorry - I may have been a little ambiguous! I realize I also skipped over the comment "Furthermore the expressions you pass to the options, which must normally be `const`, become dynamic" which kind of rules out the renaming of the macro (e.g. to `dec_debug!`). 

Anyway, I wonder if we should remove the exclamation mark (`!`) so it matches the current parameter attribute style in Rust?

e.g.
```rust
dec!(#[run_time] radix: my_radix, exp: my_exp, 10);
```

Subtle, but effectively it's just removing the exclamation mark in the `run_time` attribute. e.g. see here for an example: https://rust-lang.github.io/rfcs/2565-formal-function-parameter-attributes.html

Regarding the feature gate - I think yes for prelude for sure. Ideally it'd be the macro too (e.g. wrap in a `mod` with a conditional use perhaps?) however if it's too tricky then it's probably not that problematic to keep it.

2025-02-15 11:30 UTC, daniel-pfeiffer commented on src/str.rs
> +    (#![run_time] $($rest:tt)+) => {
For the exclamation mark I don’t care, it’s your call. In this case it doesn’t matter, because it’s only emulating an attribute.

However you don’t seem to realise its meaning. Here are two equivalent ways of adding an attribute. When putting it inside the block (or a module…) it pertains to, Rust needs the exclamation mark. Else it would pertain to one next item.

```rust
#[doc = "same as /// as an outer attribute\n"]
fn f() {
    #![doc = "same as ///, but as an inner attribute"]
}
```

2025-02-15 16:25 UTC, paupino commented on src/str.rs
> +    (#![run_time] $($rest:tt)+) => {
I see what you mean - it pertains to all arguments in this case and changes the macro behavior itself. 

Ok, cool let's just keep it. Thanks for working through this!

2025-02-23 01:28 UTC, paupino approved these changes

2025-02-23 01:28 UTC, merged

2025-02-23 01:29 UTC, paupino commented
Thank you for your help!